# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ISO 3166-1 alpha-2 code')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number', models.IntegerField()),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.FileField(blank=True, upload_to='logos/')),
                ('gold_threshold', models.FloatField(blank=True, null=True)),
                ('silver_threshold', models.FloatField(blank=True, null=True)),
                ('bronze_threshold', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.Country')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_shirt_size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, null=True)),
                ('function', models.CharField(choices=[('PAR', 'participant'), ('LEA', 'team leader'), ('OOC', 'out of competition'), ('ORG', 'organization committee'), ('SC', 'scientific committee'), ('TC', 'technical committee'), ('GUE', 'guest')], default='participant', max_length=3)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.Country')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.Olympiad')),
            ],
            options={
                'ordering': ['olympiad', 'person'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(blank=True, null=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.Participation')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shortcut', models.CharField(max_length=10)),
                ('test', models.BooleanField(default=False, verbose_name='Test task (not counted in final score)?')),
                ('day', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2')], null=True)),
                ('statement', models.FileField(blank=True, null=True, upload_to='')),
                ('solution', models.FileField(blank=True, null=True, upload_to='')),
                ('tests', models.FileField(blank=True, null=True, upload_to='')),
                ('spoiler', models.FileField(blank=True, null=True, upload_to='')),
                ('perfect_score', models.FloatField(default=100.0)),
                ('olympiad', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='olymp.Olympiad')),
            ],
            options={
                'ordering': ['olympiad', 'day', 'shortcut'],
            },
        ),
        migrations.AddField(
            model_name='score',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.Task'),
        ),
        migrations.AddField(
            model_name='participation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.Person'),
        ),
    ]
