# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0002_auto_20170415_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='start_date',
            field=models.DateField(),
        ),
    ]
