# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0004_olympiad_president'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiad',
            name='president',
        ),
        migrations.AlterField(
            model_name='participation',
            name='function',
            field=models.CharField(choices=[('PAR', 'participant'), ('LEA', 'team leader'), ('OOC', 'second team (out of competition)'), ('PRE', 'president of the competition'), ('ORG', 'organization committee'), ('SC', 'scientific committee'), ('TC', 'technical committee'), ('GUE', 'guest')], default='participant', max_length=3),
        ),
    ]
