# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0005_auto_20170415_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('statement', 'statement'), ('tests', 'tests'), ('solution', 'solution'), ('spoiler', 'spoiler'), ('other', 'other')], max_length=10, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olymp.Country')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olymp.Task')),
            ],
        ),
    ]
