# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0007_auto_20170501_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='file',
            field=models.FileField(blank=True, upload_to='tasks/'),
        ),
    ]
