# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170305_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendedflatpage',
            options={'ordering': ['order']},
        ),
    ]
